mutation CreateProduct($input: ProductInput!) {
  createProduct(input: $input) {
    product {
      id
      title
      description
      unitOfMeasurement
      materialType
      createdAt
      updatedAt
    }
    errors {
      field
      message
    }
  }
}
